spring:
  application:
    name: asset-system
  datasource:
    url: jdbc:mysql://localhost:3306/asset_system?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      id-type: assign_id

server:
  port: 8080
